server {
    listen ${NGINX_PORT_HTTP};
    server_name ${SERVER_NAMES};

    return 301 https://$host$request_uri;
}

server {
    listen ${NGINX_PORT_HTTPS} ssl;
    server_name ${SERVER_NAMES};

    ssl_certificate_key /etc/nginx/conf.d/nginx-selfsigned.key;
    ssl_certificate /etc/nginx/conf.d/nginx-selfsigned.crt;

    root /usr/share/nginx/web/dist;
    index index.html;

    location / {
        try_files $uri $uri.html $uri/ =404;
    }

    location /api/ {
        proxy_pass http://${API_NAME}:${API_PORT};
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

# server {
#     listen ${NGINX_PORT_HTTP};
#     server_name ${DASHBOARD_SERVER_NAMES};
#     root /usr/share/nginx/dashboard;
#     index index.html;
#
#     client_max_body_size 20M;
#
#     location / {
#         try_files $uri $uri.html $uri/ =404;
#     }
#
#     location /api/ {
#         proxy_pass http://${API_NAME}:${API_PORT};
#         proxy_http_version 1.1;
#         proxy_set_header Host $host;
#         proxy_set_header X-Real-IP $remote_addr;
#         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#         proxy_set_header X-Forwarded-Proto $scheme;
#     }
# }

# erver {
#     listen ${NGINX_PORT_HTTP};
#     server_name ${APP_WEB_NAME};
#
#     return 301 https://$host$request_uri;
# }

# server {
#     listen ${NGINX_PORT_HTTPS} ssl;
#     server_name ${APP_WEB_NAME};
#
#     ssl_protocols TLSv1.2 TLSv1.3;
#
#     ssl_certificate_key /etc/nginx/conf.d/privkey.pem;
#     ssl_certificate /etc/nginx/conf.d/fullchain.pem;
#
#     # ssl_certificate_key /etc/nginx/conf.d/nginx-selfsigned.key;
#     # ssl_certificate /etc/nginx/conf.d/nginx-selfsigned.crt;
#
#     root /usr/share/nginx/html;
#     index index.html;
#
#     location = /index.html {
#       add_header Cache-Control "no-cache";
#       try_files $uri =404;
#     }
#
#     location /assets/ {
#       expires 1y;
#       add_header Cache-Control "public, max-age=31536000, immutable";
#       try_files $uri =404;
#     }
#
#     location /locales/ {
#       expires 1h;
#       add_header Cache-Control "public, max-age=3600";
#       try_files $uri =404;
#     }
#
#     location / {
#         try_files $uri /index.html;
#     }
#
#     location ~ ^/(api|sanctum|auth) {
#         proxy_pass https://${BACKEND_NGINX_NAME}:${BACKEND_NGINX_PORT};
#         proxy_ssl_verify off;
#
#         proxy_set_header Host $host;
#         proxy_set_header X-Real-IP $remote_addr;
#         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#         proxy_set_header X-Forwarded-Proto $scheme;
#         proxy_set_header X-Forwarded-Host $host;
#         proxy_set_header X-Forwarded-Port $server_port;
#     }
# }
